spring:
  application:
    name: report-service
  datasource:
    url: ${PG_URL:jdbc:postgresql://postgres:5432/reportdb}
    username: ${PG_USERNAME:postgres}
    password: ${PG_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    show-sql: false

server:
  port: 8085

jwt:
  secret: ${JWT_SECRET:mySecretKeyForJWTTokenGenerationThisShouldBeVeryLongAndSecure123456789}
  expiration: 86400000 # 24 hours in milliseconds
  refresh-expiration: 604800000 # 7 days in milliseconds

logging:
  level:
    root: INFO
    com.vladnekrasov: DEBUG
    # Remove these debug logs for cleaner output
    # org.springframework.boot.autoconfigure: DEBUG
    # org.springframework.jdbc.datasource: DEBUG
    # com.zaxxer.hikari: DEBUG

resend:
  api-key: ${RESEND_API_KEY:your-resend-api-key}
  from-email: ${RESEND_FROM_EMAIL:noreply@hraiassistant.ru}

mail:
  host: ${RESEND_SMTP_HOST:smtp.resend.com}
  port: ${RESEND_SMTP_PORT:587}
  username: ${RESEND_SMTP_USERNAME:resend}
  password: ${RESEND_API_KEY:eqweq}
  properties:
    mail:
      smtp:
        auth: true
        starttls:
          enable: true
        ssl:
          trust: smtp.resend.com
