spring:
  application:
    name: report-service
  datasource:
    url: ${PG_URL:jdbc:postgresql://postgres:5432/reportdb}
    username: ${PG_USERNAME:postgres}
    password: ${PG_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: false

server:
  port: ${REPORT_SERVICE_PORT:8086}

jwt:
  secret: ${JWT_SECRET:mySecretKeyForJWTTokenGenerationThisShouldBeVeryLongAndSecure123456789}
  expiration: 86400000 # 24 hours in milliseconds
  refresh-expiration: 604800000 # 7 days in milliseconds

logging:
  level:
    root: INFO
    com.vladnekrasov: DEBUG
    # Remove these debug logs for cleaner output
    # org.springframework.boot.autoconfigure: DEBUG
    # org.springframework.jdbc.datasource: DEBUG
    # com.zaxxer.hikari: DEBUG
